# Generated by Django 4.2.16 on 2024-10-19 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
