# Generated by Django 4.2.16 on 2024-10-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_production_fabric_alter_production_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='fabric',
            field=models.CharField(choices=[('40 S + 20 D', '40 S + 20 D'), ('34 S + 20 D', '34 S + 20 D'), ('30 S + 40 D', '30 S + 40 D'), ('HELPER', 'HELPER'), ('SERVICE', 'SERVICE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Over Night', 'Over Night')], max_length=25),
        ),
    ]
