# Generated by Django 4.2.16 on 2024-10-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_production_fabric_alter_production_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('Pipe Line', 'Pipe Line'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Done', 'Done'), ('Due', 'Due')], max_length=25),
        ),
    ]
